version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    image: postgres:15-alpine
    container_name: widget-feed-postgres-dev
    environment:
      POSTGRES_DB: widget_feed_dev
      POSTGRES_USER: widget_user
      POSTGRES_PASSWORD: widget_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - widget-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U widget_user -d widget_feed_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgreSQL Database for Testing
  postgres-test:
    image: postgres:15-alpine
    container_name: widget-feed-postgres-test
    environment:
      POSTGRES_DB: widget_feed_test
      POSTGRES_USER: widget_user
      POSTGRES_PASSWORD: widget_pass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - widget-network
    profiles:
      - testing
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U widget_user -d widget_feed_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Flyway Migration Tool
  flyway:
    image: flyway/flyway:9.22.3-alpine
    container_name: widget-feed-flyway
    command: -url=jdbc:postgresql://postgres-dev:5432/widget_feed_dev -user=widget_user -password=widget_pass -connectRetries=60 migrate
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/flyway.conf:/flyway/conf/flyway.conf
    networks:
      - widget-network
    depends_on:
      postgres-dev:
        condition: service_healthy
    profiles:
      - migration

  # Flyway for Test Database
  flyway-test:
    image: flyway/flyway:9.22.3-alpine
    container_name: widget-feed-flyway-test
    command: -url=jdbc:postgresql://postgres-test:5432/widget_feed_test -user=widget_user -password=widget_pass -connectRetries=60 migrate
    volumes:
      - ./database/migrations:/flyway/sql
      - ./database/flyway.conf:/flyway/conf/flyway.conf
    networks:
      - widget-network
    depends_on:
      postgres-test:
        condition: service_healthy
    profiles:
      - testing

volumes:
  postgres_dev_data:
    driver: local

networks:
  widget-network:
    driver: bridge
